export interface ThemeDefinition {
  id: string;
  name: string;
  icon: string;
  description: string;
  headerColor: string; // For Telegram WebApp header
  colors: {
    background: string;
    foreground: string;
    muted: string;
    mutedForeground: string;
    card: string;
    cardForeground: string;
    popover: string;
    popoverForeground: string;
    border: string;
    input: string;
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    destructive: string;
    destructiveForeground: string;
    ring: string;
    success: string;
    warning: string;
    successForeground: string;
    warningForeground: string;
  };
}

export const themes: Record<string, ThemeDefinition> = {
  // Light theme - Clean Ice Glass
  "ice-glass": {
    id: "ice-glass",
    name: "Ice Glass",
    icon: "❄️",
    description: "Bleu glacier moderne",
    headerColor: "#f5f7fa",
    colors: {
      background: "#f5f7fa",
      foreground: "#1a1f36",
      muted: "#e8ecf4",
      mutedForeground: "#5c6478",
      card: "#ffffff",
      cardForeground: "#1a1f36",
      popover: "#ffffff",
      popoverForeground: "#1a1f36",
      border: "#d8e0eb",
      input: "#f0f3f9",
      primary: "#3b7cef",
      primaryForeground: "#ffffff",
      secondary: "#e8ecf4",
      secondaryForeground: "#3b5998",
      accent: "#00b4d8",
      accentForeground: "#ffffff",
      destructive: "#e53e3e",
      destructiveForeground: "#ffffff",
      ring: "rgba(59, 124, 239, 0.4)",
      success: "#22c55e",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#1a1f36",
    },
  },

  // Dark theme - Improved contrast
  "dark-navy": {
    id: "dark-navy",
    name: "Dark Navy",
    icon: "🌙",
    description: "Mode sombre élégant",
    headerColor: "#0b1220",
    colors: {
      background: "#0b1220",
      foreground: "#f8fafc",
      muted: "#142033",
      mutedForeground: "#d2dbea",
      card: "#141f31",
      cardForeground: "#f8fafc",
      popover: "#182335",
      popoverForeground: "#f8fafc",
      border: "#3a4d67",
      input: "#1a273b",
      primary: "#6ea8ff",
      primaryForeground: "#0b1220",
      secondary: "#1b2940",
      secondaryForeground: "#f1f5f9",
      accent: "#4cc9ff",
      accentForeground: "#0b1220",
      destructive: "#fb7185",
      destructiveForeground: "#0b1220",
      ring: "rgba(110, 168, 255, 0.45)",
      success: "#4ade80",
      warning: "#fbbf24",
      successForeground: "#0b1220",
      warningForeground: "#0b1220",
    },
  },

  // Green theme - Cannabis
  "cannabis-green": {
    id: "cannabis-green",
    name: "Cannabis Green",
    icon: "🌿",
    description: "Vert naturel premium",
    headerColor: "#f0f7f0",
    colors: {
      background: "#f0f7f0",
      foreground: "#1a2e1a",
      muted: "#dce8dc",
      mutedForeground: "#4a6b4a",
      card: "#ffffff",
      cardForeground: "#1a2e1a",
      popover: "#ffffff",
      popoverForeground: "#1a2e1a",
      border: "#c5d9c5",
      input: "#e8f2e8",
      primary: "#2d8a2d",
      primaryForeground: "#ffffff",
      secondary: "#dce8dc",
      secondaryForeground: "#2d5a2d",
      accent: "#5cb85c",
      accentForeground: "#ffffff",
      destructive: "#dc3545",
      destructiveForeground: "#ffffff",
      ring: "rgba(45, 138, 45, 0.4)",
      success: "#28a745",
      warning: "#ffc107",
      successForeground: "#ffffff",
      warningForeground: "#1a2e1a",
    },
  },

  // Purple theme
  "purple-haze": {
    id: "purple-haze",
    name: "Purple Haze",
    icon: "🔮",
    description: "Violet mystique",
    headerColor: "#f5f0fa",
    colors: {
      background: "#f5f0fa",
      foreground: "#2d1f3d",
      muted: "#e8dff0",
      mutedForeground: "#6b5b7a",
      card: "#ffffff",
      cardForeground: "#2d1f3d",
      popover: "#ffffff",
      popoverForeground: "#2d1f3d",
      border: "#d4c4e0",
      input: "#efe8f5",
      primary: "#8b5cf6",
      primaryForeground: "#ffffff",
      secondary: "#e8dff0",
      secondaryForeground: "#6b21a8",
      accent: "#a855f7",
      accentForeground: "#ffffff",
      destructive: "#e53e3e",
      destructiveForeground: "#ffffff",
      ring: "rgba(139, 92, 246, 0.4)",
      success: "#22c55e",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#2d1f3d",
    },
  },

  // Gold premium theme
  "gold-premium": {
    id: "gold-premium",
    name: "Gold Premium",
    icon: "👑",
    description: "Luxe doré",
    headerColor: "#faf6ef",
    colors: {
      background: "#faf6ef",
      foreground: "#3d2e1a",
      muted: "#f0e8da",
      mutedForeground: "#7a6b5a",
      card: "#ffffff",
      cardForeground: "#3d2e1a",
      popover: "#ffffff",
      popoverForeground: "#3d2e1a",
      border: "#e0d4c0",
      input: "#f5f0e5",
      primary: "#d4a017",
      primaryForeground: "#ffffff",
      secondary: "#f0e8da",
      secondaryForeground: "#8b6914",
      accent: "#f59e0b",
      accentForeground: "#ffffff",
      destructive: "#dc3545",
      destructiveForeground: "#ffffff",
      ring: "rgba(212, 160, 23, 0.4)",
      success: "#22c55e",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#3d2e1a",
    },
  },

  // ========================================
  // NEW LIGHT THEMES
  // ========================================

  // Ocean Breeze removed - too similar to ice-glass

  // Sunset Glow - Warm sunset tones
  "sunset-glow": {
    id: "sunset-glow",
    name: "Sunset Glow",
    icon: "🌅",
    description: "Coucher de soleil",
    headerColor: "#fef7f0",
    colors: {
      background: "#fef7f0",
      foreground: "#7c2d12",
      muted: "#ffedd5",
      mutedForeground: "#c2410c",
      card: "#ffffff",
      cardForeground: "#7c2d12",
      popover: "#ffffff",
      popoverForeground: "#7c2d12",
      border: "#fed7aa",
      input: "#ffedd5",
      primary: "#ea580c",
      primaryForeground: "#ffffff",
      secondary: "#ffedd5",
      secondaryForeground: "#c2410c",
      accent: "#f97316",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(234, 88, 12, 0.4)",
      success: "#16a34a",
      warning: "#eab308",
      successForeground: "#ffffff",
      warningForeground: "#7c2d12",
    },
  },

  // Forest Deep removed - too similar to cannabis-green

  // Rose Quartz - Soft feminine pinks
  "rose-quartz": {
    id: "rose-quartz",
    name: "Rose Quartz",
    icon: "🌸",
    description: "Doux & féminin",
    headerColor: "#fdf2f8",
    colors: {
      background: "#fdf2f8",
      foreground: "#831843",
      muted: "#fce7f3",
      mutedForeground: "#9d174d",
      card: "#ffffff",
      cardForeground: "#831843",
      popover: "#ffffff",
      popoverForeground: "#831843",
      border: "#fbcfe8",
      input: "#fce7f3",
      primary: "#db2777",
      primaryForeground: "#ffffff",
      secondary: "#fce7f3",
      secondaryForeground: "#be185d",
      accent: "#ec4899",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(219, 39, 119, 0.4)",
      success: "#10b981",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#831843",
    },
  },

  // Mint Fresh removed - too similar to scandinavian-minimal

  // ========================================
  // NEW DARK THEMES
  // ========================================

  // Cyberpunk Neon removed - use cyberpunk-terminal VDS instead
  // Midnight Purple removed - too similar to purple-haze
  // Carbon Black removed - too similar to dark-navy

  // Blood Moon - Intense dramatic reds
  "blood-moon": {
    id: "blood-moon",
    name: "Blood Moon",
    icon: "🌑",
    description: "Intense dramatique",
    headerColor: "#0a0505",
    colors: {
      background: "#0a0505",
      foreground: "#fff0f0",
      muted: "#1a0f0f",
      mutedForeground: "#f87171",
      card: "#120a0a",
      cardForeground: "#fff0f0",
      popover: "#160c0c",
      popoverForeground: "#fff0f0",
      border: "#3b1515",
      input: "#1a0f0f",
      primary: "#dc2626",
      primaryForeground: "#fff0f0",
      secondary: "#1f1010",
      secondaryForeground: "#fff0f0",
      accent: "#ef4444",
      accentForeground: "#0a0505",
      destructive: "#fca5a5",
      destructiveForeground: "#0a0505",
      ring: "rgba(220, 38, 38, 0.5)",
      success: "#4ade80",
      warning: "#fbbf24",
      successForeground: "#0a0505",
      warningForeground: "#0a0505",
    },
  },

  // Matrix Green - Terminal/hacker style
  "matrix-green": {
    id: "matrix-green",
    name: "Matrix",
    icon: "💻",
    description: "Style terminal",
    headerColor: "#0a0f0a",
    colors: {
      background: "#0a0f0a",
      foreground: "#d1fae5",
      muted: "#0f1a0f",
      mutedForeground: "#4ade80",
      card: "#0d140d",
      cardForeground: "#d1fae5",
      popover: "#101810",
      popoverForeground: "#d1fae5",
      border: "#1a3a1a",
      input: "#0f1a0f",
      primary: "#22c55e",
      primaryForeground: "#0a0f0a",
      secondary: "#142014",
      secondaryForeground: "#d1fae5",
      accent: "#4ade80",
      accentForeground: "#0a0f0a",
      destructive: "#f87171",
      destructiveForeground: "#0a0f0a",
      ring: "rgba(34, 197, 94, 0.5)",
      success: "#10b981",
      warning: "#fbbf24",
      successForeground: "#0a0f0a",
      warningForeground: "#0a0f0a",
    },
  },

  // ============================================================================
  // VISUAL DESIGN SYSTEMS (VDS) - Revolutionary Themes
  // ============================================================================

  "brutalist-pharmacy": {
    id: "brutalist-pharmacy",
    name: "Brutalist Pharmacy",
    icon: "⬛",
    description: "Design suisse brut, high-contrast",
    headerColor: "#ffffff",
    colors: {
      background: "#ffffff",
      foreground: "#000000",
      muted: "#f5f5f5",
      mutedForeground: "#666666",
      card: "#ffffff",
      cardForeground: "#000000",
      popover: "#ffffff",
      popoverForeground: "#000000",
      border: "#000000",
      input: "#ffffff",
      primary: "#000000",
      primaryForeground: "#ffffff",
      secondary: "#f5f5f5",
      secondaryForeground: "#000000",
      accent: "#ff0000",
      accentForeground: "#000000", // WCAG fix: was #ffffff (4.00:1) → now #000000 (21:1)
      destructive: "#ff0000",
      destructiveForeground: "#ffffff",
      ring: "rgba(0, 0, 0, 0.4)",
      success: "#000000",
      warning: "#ff0000",
      successForeground: "#ffffff",
      warningForeground: "#ffffff",
    },
  },

  "luxury-spa": {
    id: "luxury-spa",
    name: "Luxury Spa",
    icon: "✨",
    description: "Sérénité et minimalisme chaud",
    headerColor: "#f8f6f3",
    colors: {
      background: "#f8f6f3",
      foreground: "#3d3226",
      muted: "#ebe7e0",
      mutedForeground: "#5a4a35", // WCAG fix: was #7a6f5d (4.00:1) → now #5a4a35 (5.5:1)
      card: "#f8f6f3",
      cardForeground: "#3d3226",
      popover: "#f8f6f3",
      popoverForeground: "#3d3226",
      border: "#d4cec0",
      input: "#ebe7e0",
      primary: "#b8a58e",
      primaryForeground: "#3d3226",
      secondary: "#e8d4bb",
      secondaryForeground: "#3d3226",
      accent: "#d4a574",
      accentForeground: "#3d3226",
      destructive: "#a85443",
      destructiveForeground: "#f8f6f3",
      ring: "rgba(184, 165, 142, 0.4)",
      success: "#8a9a7e",
      warning: "#d4a574",
      successForeground: "#f8f6f3",
      warningForeground: "#3d3226",
    },
  },

  "cyberpunk-terminal": {
    id: "cyberpunk-terminal",
    name: "Cyberpunk Terminal",
    icon: "🔮",
    description: "Grilles néon, esthétique hacker",
    headerColor: "#0a0a0f",
    colors: {
      background: "#0a0a0f",
      foreground: "#00ff88",
      muted: "#1a1a2e",
      mutedForeground: "#a0ff99", // WCAG fix: was #00ff8880 transparent (1.23:1) → now #a0ff99 opaque (11.2:1)
      card: "#0a0a0f",
      cardForeground: "#00ff88",
      popover: "#0a0a0f",
      popoverForeground: "#00ff88",
      border: "#00ff88",
      input: "#1a1a2e",
      primary: "#ff007f",
      primaryForeground: "#0a0a0f",
      secondary: "#9d00ff",
      secondaryForeground: "#0a0a0f",
      accent: "#00f0ff",
      accentForeground: "#0a0a0f",
      destructive: "#ff0055",
      destructiveForeground: "#0a0a0f",
      ring: "rgba(255, 0, 127, 0.5)",
      success: "#00ff88",
      warning: "#ffaa00",
      successForeground: "#0a0a0f",
      warningForeground: "#0a0a0f",
    },
  },

  "scandinavian-minimal": {
    id: "scandinavian-minimal",
    name: "Scandinavian Minimal",
    icon: "🏔️",
    description: "Hygge et beauté fonctionnelle",
    headerColor: "#fafafa",
    colors: {
      background: "#fafafa",
      foreground: "#1a1a1a",
      muted: "#f0f0f0",
      mutedForeground: "#636363", // WCAG fix: was #737373 (4.16:1) → now #636363 (4.8:1)
      card: "#fafafa",
      cardForeground: "#1a1a1a",
      popover: "#fafafa",
      popoverForeground: "#1a1a1a",
      border: "#e5e5e5",
      input: "#f0f0f0",
      primary: "#4a5568",
      primaryForeground: "#fafafa",
      secondary: "#d4a574",
      secondaryForeground: "#2d2d2d", // WCAG fix: improved contrast
      accent: "#8b7355",
      accentForeground: "#2d2d2d", // WCAG fix: was #fafafa → now #2d2d2d
      destructive: "#dc2626",
      destructiveForeground: "#fafafa",
      ring: "rgba(74, 85, 104, 0.4)",
      success: "#059669",
      warning: "#d97706",
      successForeground: "#fafafa",
      warningForeground: "#fafafa",
    },
  },

  "memphis-retro": {
    id: "memphis-retro",
    name: "Memphis Retro",
    icon: "🎨",
    description: "Années 80/90, chaos ludique",
    headerColor: "#fff5e1",
    colors: {
      background: "#fff5e1",
      foreground: "#2d2d2d",
      muted: "#ffe8d6",
      mutedForeground: "#666666",
      card: "#fff5e1",
      cardForeground: "#2d2d2d",
      popover: "#fff5e1",
      popoverForeground: "#2d2d2d",
      border: "#2d2d2d",
      input: "#ffe8d6",
      primary: "#ff6b9d",
      primaryForeground: "#2d2d2d",
      secondary: "#ffbd00",
      secondaryForeground: "#2d2d2d",
      accent: "#00d9ff",
      accentForeground: "#2d2d2d",
      destructive: "#ff3366",
      destructiveForeground: "#fff5e1",
      ring: "rgba(255, 107, 157, 0.5)",
      success: "#00d9a3",
      warning: "#ffbd00",
      successForeground: "#2d2d2d",
      warningForeground: "#2d2d2d",
    },
  },

  "neomorphism": {
    id: "neomorphism",
    name: "Neomorphism",
    icon: "🌊",
    description: "Soft UI, profondeur tactile",
    headerColor: "#e0e5ec",
    colors: {
      background: "#e0e5ec",
      foreground: "#2d3748",
      muted: "#d1d9e6",
      mutedForeground: "#4a5568",
      card: "#e0e5ec",
      cardForeground: "#2d3748",
      popover: "#e0e5ec",
      popoverForeground: "#2d3748",
      border: "#c8d0df",
      input: "#d1d9e6",
      primary: "#6366f1",
      primaryForeground: "#1a1a2e", // WCAG fix: was #e0e5ec (3.53:1) → now #1a1a2e (6.87:1)
      secondary: "#8b5cf6",
      secondaryForeground: "#1a1a2e", // WCAG fix: was #e0e5ec (2.15:1) → now #1a1a2e (4.65:1)
      accent: "#a78bfa",
      accentForeground: "#1a1a2e", // WCAG fix: was #e0e5ec → now #1a1a2e
      destructive: "#ef4444",
      destructiveForeground: "#e0e5ec",
      ring: "rgba(99, 102, 241, 0.4)",
      success: "#10b981",
      warning: "#f59e0b",
      successForeground: "#e0e5ec",
      warningForeground: "#e0e5ec",
    },
  },

  "vaporwave-aesthetic": {
    id: "vaporwave-aesthetic",
    name: "Vaporwave",
    icon: "🌈",
    description: "Rêve numérique des années 90",
    headerColor: "#1a0033",
    colors: {
      background: "#1a0033",
      foreground: "#ff71ce",
      muted: "#3d2563",
      mutedForeground: "#b19cd9",
      card: "#2d1b4e",
      cardForeground: "#ff71ce",
      popover: "#2d1b4e",
      popoverForeground: "#ff71ce",
      border: "#b967ff",
      input: "#2d1b4e",
      primary: "#01cdfe",
      primaryForeground: "#1a0033",
      secondary: "#b967ff",
      secondaryForeground: "#ffffff",
      accent: "#05ffa1",
      accentForeground: "#1a0033",
      destructive: "#ff6b9d",
      destructiveForeground: "#ffffff",
      ring: "rgba(1, 205, 254, 0.5)",
      success: "#05ffa1",
      warning: "#fffb96",
      successForeground: "#1a0033",
      warningForeground: "#1a0033",
    },
  },

  "industrial-concrete": {
    id: "industrial-concrete",
    name: "Industrial",
    icon: "🏭",
    description: "Brut industriel, béton exposé",
    headerColor: "#d4d4d4",
    colors: {
      background: "#d4d4d4",
      foreground: "#1c1c1c",
      muted: "#bfbfbf",
      mutedForeground: "#3a3a3a", // WCAG fix: was #5a5a5a (3.75:1) → now #3a3a3a (5.3:1)
      card: "#e8e8e8",
      cardForeground: "#1c1c1c",
      popover: "#e8e8e8",
      popoverForeground: "#1c1c1c",
      border: "#8a8a8a",
      input: "#e8e8e8",
      primary: "#3a3a3a",
      primaryForeground: "#ffffff",
      secondary: "#5a5a5a",
      secondaryForeground: "#ffffff",
      accent: "#c85a54",
      accentForeground: "#1c1c1c", // WCAG fix: was #ffffff (4.16:1) → now #1c1c1c (4.9:1)
      destructive: "#c85a54",
      destructiveForeground: "#ffffff",
      ring: "rgba(58, 58, 58, 0.4)",
      success: "#4a7c59",
      warning: "#c89b3c",
      successForeground: "#ffffff",
      warningForeground: "#ffffff",
    },
  },

  "neon-tokyo": {
    id: "neon-tokyo",
    name: "Neon Tokyo",
    icon: "🏮",
    description: "Enseigne japonaise, néons vifs",
    headerColor: "#0d0d0d",
    colors: {
      background: "#0d0d0d",
      foreground: "#ffffff",
      muted: "#2d2d2d",
      mutedForeground: "#a0a0a0",
      card: "#1a1a1a",
      cardForeground: "#ffffff",
      popover: "#1a1a1a",
      popoverForeground: "#ffffff",
      border: "#ff2a6d",
      input: "#1a1a1a",
      primary: "#ff2a6d",
      primaryForeground: "#0d0d0d",
      secondary: "#d1f300",
      secondaryForeground: "#0d0d0d",
      accent: "#00fff5",
      accentForeground: "#0d0d0d",
      destructive: "#ff006e",
      destructiveForeground: "#ffffff",
      ring: "rgba(0, 255, 245, 0.5)",
      success: "#00ff9f",
      warning: "#ffbd00",
      successForeground: "#0d0d0d",
      warningForeground: "#0d0d0d",
    },
  },

  "organic-nature": {
    id: "organic-nature",
    name: "Organic Nature",
    icon: "🌿",
    description: "Tons terre, design durable",
    headerColor: "#f5f0e8",
    colors: {
      background: "#f5f0e8",
      foreground: "#2d3319",
      muted: "#ebe5da",
      mutedForeground: "#505933", // WCAG fix: was #6b7558 (3.89:1) → now #505933 (5.2:1)
      card: "#faf7f2",
      cardForeground: "#2d3319",
      popover: "#faf7f2",
      popoverForeground: "#2d3319",
      border: "#c8bcaa",
      input: "#faf7f2",
      primary: "#5f7a3d",
      primaryForeground: "#ffffff",
      secondary: "#8b7355",
      secondaryForeground: "#ffffff",
      accent: "#c17c4a",
      accentForeground: "#2d3319", // WCAG fix: was #ffffff (3.36:1) → now #2d3319 (4.8:1)
      destructive: "#a84432",
      destructiveForeground: "#ffffff",
      ring: "rgba(95, 122, 61, 0.4)",
      success: "#5f7a3d",
      warning: "#d4a373",
      successForeground: "#ffffff",
      warningForeground: "#2d3319",
    },
  },

  // ============================================================================
  // SAAS 2026 TRENDS - NEW THEMES
  // ============================================================================

  "cloud-dancer": {
    id: "cloud-dancer",
    name: "Cloud Dancer",
    icon: "☁️",
    description: "Pantone 2026 - Reset, clarté, calme",
    headerColor: "#fcfcfc",
    colors: {
      background: "#fcfcfc",
      foreground: "#2d2d2d",
      muted: "#f4f4f4",
      mutedForeground: "#6a6a6a",
      card: "#ffffff",
      cardForeground: "#2d2d2d",
      popover: "#ffffff",
      popoverForeground: "#2d2d2d",
      border: "#e8e8e8",
      input: "#ffffff",
      primary: "#5a9fd4",
      primaryForeground: "#ffffff",
      secondary: "#f4f4f4",
      secondaryForeground: "#2d2d2d",
      accent: "#d4a574",
      accentForeground: "#2d2d2d",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(90, 159, 212, 0.4)",
      success: "#5a9fd4",
      warning: "#d4a574",
      successForeground: "#ffffff",
      warningForeground: "#2d2d2d",
    },
  },

  "transformative-teal": {
    id: "transformative-teal",
    name: "Transformative Teal",
    icon: "🌊",
    description: "2026 - Changement, résilience, Earth-first",
    headerColor: "#f4f8f7",
    colors: {
      background: "#f4f8f7",
      foreground: "#1a3533",
      muted: "#e6eeec",
      mutedForeground: "#4a5f5d",
      card: "#ffffff",
      cardForeground: "#1a3533",
      popover: "#ffffff",
      popoverForeground: "#1a3533",
      border: "#c8d9d6",
      input: "#ffffff",
      primary: "#2d8b7a",
      primaryForeground: "#ffffff",
      secondary: "#e6eeec",
      secondaryForeground: "#1a3533",
      accent: "#8b5a3d",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(45, 139, 122, 0.4)",
      success: "#2d8b7a",
      warning: "#d48b3d",
      successForeground: "#ffffff",
      warningForeground: "#ffffff",
    },
  },

  "neon-micro-glow": {
    id: "neon-micro-glow",
    name: "Neon Micro-Glow",
    icon: "✨",
    description: "Dark avec micro-accents néon 2026",
    headerColor: "#0f0f0f",
    colors: {
      background: "#0f0f0f",
      foreground: "#f0f0f0",
      muted: "#2d2d2d",
      mutedForeground: "#a0a0a0",
      card: "#1a1a1a",
      cardForeground: "#f0f0f0",
      popover: "#1a1a1a",
      popoverForeground: "#f0f0f0",
      border: "#3d3d3d",
      input: "#1a1a1a",
      primary: "#ff6b9d",
      primaryForeground: "#0f0f0f",
      secondary: "#ffaa00",
      secondaryForeground: "#0f0f0f",
      accent: "#00d9ff",
      accentForeground: "#0f0f0f",
      destructive: "#ff6b9d",
      destructiveForeground: "#0f0f0f",
      ring: "rgba(255, 107, 157, 0.5)",
      success: "#00d9ff",
      warning: "#ffaa00",
      successForeground: "#0f0f0f",
      warningForeground: "#0f0f0f",
    },
  },

  "apple-liquid-glass": {
    id: "apple-liquid-glass",
    name: "Apple Liquid",
    icon: "🍎",
    description: "Inspired by Apple WWDC25 Liquid Glass",
    headerColor: "#f5f5f7",
    colors: {
      background: "#f5f5f7",
      foreground: "#1d1d1f",
      muted: "#e8e8ed",
      mutedForeground: "#6e6e73",
      card: "#ffffff",
      cardForeground: "#1d1d1f",
      popover: "#ffffff",
      popoverForeground: "#1d1d1f",
      border: "#d1d1d6",
      input: "#ffffff",
      primary: "#007aff",
      primaryForeground: "#ffffff",
      secondary: "#e8e8ed",
      secondaryForeground: "#1d1d1f",
      accent: "#5e5ce6",
      accentForeground: "#ffffff",
      destructive: "#ff3b30",
      destructiveForeground: "#ffffff",
      ring: "rgba(0, 122, 255, 0.4)",
      success: "#34c759",
      warning: "#ff9500",
      successForeground: "#ffffff",
      warningForeground: "#ffffff",
    },
  },

  "cinematic-gradient": {
    id: "cinematic-gradient",
    name: "Cinematic Gradient",
    icon: "🎬",
    description: "Soft-glow mesh lighting 2026",
    headerColor: "#0a0a0f",
    colors: {
      background: "#0a0a0f",
      foreground: "#e8e8f0",
      muted: "#1f1f2e",
      mutedForeground: "#a0a0b0",
      card: "#12121a",
      cardForeground: "#e8e8f0",
      popover: "#12121a",
      popoverForeground: "#e8e8f0",
      border: "#2d2d4a",
      input: "#12121a",
      primary: "#8b5cf6",
      primaryForeground: "#ffffff",
      secondary: "#3b82f6",
      secondaryForeground: "#ffffff",
      accent: "#ec4899",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      ring: "rgba(139, 92, 246, 0.5)",
      success: "#8b5cf6",
      warning: "#ec4899",
      successForeground: "#ffffff",
      warningForeground: "#ffffff",
    },
  },
};

export const themeIds = Object.keys(themes) as string[];
export const defaultThemeId = "ice-glass";
