export interface ThemeDefinition {
  id: string;
  name: string;
  icon: string;
  description: string;
  headerColor: string; // For Telegram WebApp header
  colors: {
    background: string;
    foreground: string;
    muted: string;
    mutedForeground: string;
    card: string;
    cardForeground: string;
    popover: string;
    popoverForeground: string;
    border: string;
    input: string;
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    destructive: string;
    destructiveForeground: string;
    ring: string;
    success: string;
    warning: string;
    successForeground: string;
    warningForeground: string;
  };
}

export const themes: Record<string, ThemeDefinition> = {
  // Light theme - Clean Ice Glass
  "ice-glass": {
    id: "ice-glass",
    name: "Ice Glass",
    icon: "❄️",
    description: "Bleu glacier moderne",
    headerColor: "#f5f7fa",
    colors: {
      background: "#f5f7fa",
      foreground: "#1a1f36",
      muted: "#e8ecf4",
      mutedForeground: "#5c6478",
      card: "#ffffff",
      cardForeground: "#1a1f36",
      popover: "#ffffff",
      popoverForeground: "#1a1f36",
      border: "#d8e0eb",
      input: "#f0f3f9",
      primary: "#3b7cef",
      primaryForeground: "#ffffff",
      secondary: "#e8ecf4",
      secondaryForeground: "#3b5998",
      accent: "#00b4d8",
      accentForeground: "#ffffff",
      destructive: "#e53e3e",
      destructiveForeground: "#ffffff",
      ring: "rgba(59, 124, 239, 0.4)",
      success: "#22c55e",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#1a1f36",
    },
  },

  // Dark theme - Improved contrast
  "dark-navy": {
    id: "dark-navy",
    name: "Dark Navy",
    icon: "🌙",
    description: "Mode sombre élégant",
    headerColor: "#0b1220",
    colors: {
      background: "#0b1220",
      foreground: "#f8fafc",
      muted: "#142033",
      mutedForeground: "#d2dbea",
      card: "#141f31",
      cardForeground: "#f8fafc",
      popover: "#182335",
      popoverForeground: "#f8fafc",
      border: "#3a4d67",
      input: "#1a273b",
      primary: "#6ea8ff",
      primaryForeground: "#0b1220",
      secondary: "#1b2940",
      secondaryForeground: "#f1f5f9",
      accent: "#4cc9ff",
      accentForeground: "#0b1220",
      destructive: "#fb7185",
      destructiveForeground: "#0b1220",
      ring: "rgba(110, 168, 255, 0.45)",
      success: "#4ade80",
      warning: "#fbbf24",
      successForeground: "#0b1220",
      warningForeground: "#0b1220",
    },
  },

  // Green theme - Cannabis
  "cannabis-green": {
    id: "cannabis-green",
    name: "Cannabis Green",
    icon: "🌿",
    description: "Vert naturel premium",
    headerColor: "#f0f7f0",
    colors: {
      background: "#f0f7f0",
      foreground: "#1a2e1a",
      muted: "#dce8dc",
      mutedForeground: "#4a6b4a",
      card: "#ffffff",
      cardForeground: "#1a2e1a",
      popover: "#ffffff",
      popoverForeground: "#1a2e1a",
      border: "#c5d9c5",
      input: "#e8f2e8",
      primary: "#2d8a2d",
      primaryForeground: "#ffffff",
      secondary: "#dce8dc",
      secondaryForeground: "#2d5a2d",
      accent: "#5cb85c",
      accentForeground: "#ffffff",
      destructive: "#dc3545",
      destructiveForeground: "#ffffff",
      ring: "rgba(45, 138, 45, 0.4)",
      success: "#28a745",
      warning: "#ffc107",
      successForeground: "#ffffff",
      warningForeground: "#1a2e1a",
    },
  },

  // Purple theme
  "purple-haze": {
    id: "purple-haze",
    name: "Purple Haze",
    icon: "🔮",
    description: "Violet mystique",
    headerColor: "#f5f0fa",
    colors: {
      background: "#f5f0fa",
      foreground: "#2d1f3d",
      muted: "#e8dff0",
      mutedForeground: "#6b5b7a",
      card: "#ffffff",
      cardForeground: "#2d1f3d",
      popover: "#ffffff",
      popoverForeground: "#2d1f3d",
      border: "#d4c4e0",
      input: "#efe8f5",
      primary: "#8b5cf6",
      primaryForeground: "#ffffff",
      secondary: "#e8dff0",
      secondaryForeground: "#6b21a8",
      accent: "#a855f7",
      accentForeground: "#ffffff",
      destructive: "#e53e3e",
      destructiveForeground: "#ffffff",
      ring: "rgba(139, 92, 246, 0.4)",
      success: "#22c55e",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#2d1f3d",
    },
  },

  // Gold premium theme
  "gold-premium": {
    id: "gold-premium",
    name: "Gold Premium",
    icon: "👑",
    description: "Luxe doré",
    headerColor: "#faf6ef",
    colors: {
      background: "#faf6ef",
      foreground: "#3d2e1a",
      muted: "#f0e8da",
      mutedForeground: "#7a6b5a",
      card: "#ffffff",
      cardForeground: "#3d2e1a",
      popover: "#ffffff",
      popoverForeground: "#3d2e1a",
      border: "#e0d4c0",
      input: "#f5f0e5",
      primary: "#d4a017",
      primaryForeground: "#ffffff",
      secondary: "#f0e8da",
      secondaryForeground: "#8b6914",
      accent: "#f59e0b",
      accentForeground: "#ffffff",
      destructive: "#dc3545",
      destructiveForeground: "#ffffff",
      ring: "rgba(212, 160, 23, 0.4)",
      success: "#22c55e",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#3d2e1a",
    },
  },

  // ========================================
  // NEW LIGHT THEMES
  // ========================================

  // Ocean Breeze - Fresh coastal vibes
  "ocean-breeze": {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    icon: "🌊",
    description: "Frais côtier",
    headerColor: "#f0f9fa",
    colors: {
      background: "#f0f9fa",
      foreground: "#0c4a6e",
      muted: "#e0f2fe",
      mutedForeground: "#0369a1",
      card: "#ffffff",
      cardForeground: "#0c4a6e",
      popover: "#ffffff",
      popoverForeground: "#0c4a6e",
      border: "#bae6fd",
      input: "#e0f2fe",
      primary: "#0891b2",
      primaryForeground: "#ffffff",
      secondary: "#e0f2fe",
      secondaryForeground: "#0e7490",
      accent: "#06b6d4",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(8, 145, 178, 0.4)",
      success: "#10b981",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#0c4a6e",
    },
  },

  // Sunset Glow - Warm sunset tones
  "sunset-glow": {
    id: "sunset-glow",
    name: "Sunset Glow",
    icon: "🌅",
    description: "Coucher de soleil",
    headerColor: "#fef7f0",
    colors: {
      background: "#fef7f0",
      foreground: "#7c2d12",
      muted: "#ffedd5",
      mutedForeground: "#c2410c",
      card: "#ffffff",
      cardForeground: "#7c2d12",
      popover: "#ffffff",
      popoverForeground: "#7c2d12",
      border: "#fed7aa",
      input: "#ffedd5",
      primary: "#ea580c",
      primaryForeground: "#ffffff",
      secondary: "#ffedd5",
      secondaryForeground: "#c2410c",
      accent: "#f97316",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(234, 88, 12, 0.4)",
      success: "#16a34a",
      warning: "#eab308",
      successForeground: "#ffffff",
      warningForeground: "#7c2d12",
    },
  },

  // Forest Deep - Deep forest greens
  "forest-deep": {
    id: "forest-deep",
    name: "Forest Deep",
    icon: "🌲",
    description: "Nature forestière",
    headerColor: "#f0f5f0",
    colors: {
      background: "#f0f5f0",
      foreground: "#14532d",
      muted: "#dcfce7",
      mutedForeground: "#166534",
      card: "#ffffff",
      cardForeground: "#14532d",
      popover: "#ffffff",
      popoverForeground: "#14532d",
      border: "#bbf7d0",
      input: "#dcfce7",
      primary: "#15803d",
      primaryForeground: "#ffffff",
      secondary: "#dcfce7",
      secondaryForeground: "#166534",
      accent: "#22c55e",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(21, 128, 61, 0.4)",
      success: "#16a34a",
      warning: "#ca8a04",
      successForeground: "#ffffff",
      warningForeground: "#14532d",
    },
  },

  // Rose Quartz - Soft feminine pinks
  "rose-quartz": {
    id: "rose-quartz",
    name: "Rose Quartz",
    icon: "🌸",
    description: "Doux & féminin",
    headerColor: "#fdf2f8",
    colors: {
      background: "#fdf2f8",
      foreground: "#831843",
      muted: "#fce7f3",
      mutedForeground: "#9d174d",
      card: "#ffffff",
      cardForeground: "#831843",
      popover: "#ffffff",
      popoverForeground: "#831843",
      border: "#fbcfe8",
      input: "#fce7f3",
      primary: "#db2777",
      primaryForeground: "#ffffff",
      secondary: "#fce7f3",
      secondaryForeground: "#be185d",
      accent: "#ec4899",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(219, 39, 119, 0.4)",
      success: "#10b981",
      warning: "#f59e0b",
      successForeground: "#ffffff",
      warningForeground: "#831843",
    },
  },

  // Mint Fresh - Ultra clean minimal
  "mint-fresh": {
    id: "mint-fresh",
    name: "Mint Fresh",
    icon: "🍃",
    description: "Ultra clean",
    headerColor: "#f0fdf4",
    colors: {
      background: "#f0fdf4",
      foreground: "#064e3b",
      muted: "#d1fae5",
      mutedForeground: "#047857",
      card: "#ffffff",
      cardForeground: "#064e3b",
      popover: "#ffffff",
      popoverForeground: "#064e3b",
      border: "#a7f3d0",
      input: "#d1fae5",
      primary: "#10b981",
      primaryForeground: "#ffffff",
      secondary: "#d1fae5",
      secondaryForeground: "#059669",
      accent: "#34d399",
      accentForeground: "#064e3b",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      ring: "rgba(16, 185, 129, 0.4)",
      success: "#059669",
      warning: "#d97706",
      successForeground: "#ffffff",
      warningForeground: "#064e3b",
    },
  },

  // ========================================
  // NEW DARK THEMES
  // ========================================

  // Cyberpunk Neon - Futuristic neons
  "cyberpunk-neon": {
    id: "cyberpunk-neon",
    name: "Cyberpunk",
    icon: "🌃",
    description: "Néons futuristes",
    headerColor: "#0a0a0f",
    colors: {
      background: "#0a0a0f",
      foreground: "#f0f0f5",
      muted: "#1a1a25",
      mutedForeground: "#8888aa",
      card: "#12121a",
      cardForeground: "#f0f0f5",
      popover: "#16161f",
      popoverForeground: "#f0f0f5",
      border: "#2a2a3a",
      input: "#1a1a25",
      primary: "#ff007f",
      primaryForeground: "#0a0a0f",
      secondary: "#1f1f2a",
      secondaryForeground: "#f0f0f5",
      accent: "#00f0ff",
      accentForeground: "#0a0a0f",
      destructive: "#ff3366",
      destructiveForeground: "#0a0a0f",
      ring: "rgba(255, 0, 127, 0.5)",
      success: "#00ff88",
      warning: "#ffcc00",
      successForeground: "#0a0a0f",
      warningForeground: "#0a0a0f",
    },
  },

  // Midnight Purple - Luxurious nocturnal purples
  "midnight-purple": {
    id: "midnight-purple",
    name: "Midnight",
    icon: "🔮",
    description: "Luxe nocturne",
    headerColor: "#0f0a1a",
    colors: {
      background: "#0f0a1a",
      foreground: "#f5f0ff",
      muted: "#1a1425",
      mutedForeground: "#a78bfa",
      card: "#140f1f",
      cardForeground: "#f5f0ff",
      popover: "#1a1428",
      popoverForeground: "#f5f0ff",
      border: "#3b2d50",
      input: "#1a1425",
      primary: "#a855f7",
      primaryForeground: "#0f0a1a",
      secondary: "#1f1830",
      secondaryForeground: "#f5f0ff",
      accent: "#c084fc",
      accentForeground: "#0f0a1a",
      destructive: "#f472b6",
      destructiveForeground: "#0f0a1a",
      ring: "rgba(168, 85, 247, 0.5)",
      success: "#4ade80",
      warning: "#fbbf24",
      successForeground: "#0f0a1a",
      warningForeground: "#0f0a1a",
    },
  },

  // Carbon Black - Minimalist dark
  "carbon-black": {
    id: "carbon-black",
    name: "Carbon",
    icon: "⬛",
    description: "Sombre minimaliste",
    headerColor: "#0a0a0a",
    colors: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      muted: "#171717",
      mutedForeground: "#a1a1aa",
      card: "#0f0f0f",
      cardForeground: "#fafafa",
      popover: "#141414",
      popoverForeground: "#fafafa",
      border: "#262626",
      input: "#171717",
      primary: "#fafafa",
      primaryForeground: "#0a0a0a",
      secondary: "#1c1c1c",
      secondaryForeground: "#fafafa",
      accent: "#a1a1aa",
      accentForeground: "#0a0a0a",
      destructive: "#ef4444",
      destructiveForeground: "#fafafa",
      ring: "rgba(250, 250, 250, 0.3)",
      success: "#22c55e",
      warning: "#f59e0b",
      successForeground: "#0a0a0a",
      warningForeground: "#0a0a0a",
    },
  },

  // Blood Moon - Intense dramatic reds
  "blood-moon": {
    id: "blood-moon",
    name: "Blood Moon",
    icon: "🌑",
    description: "Intense dramatique",
    headerColor: "#0a0505",
    colors: {
      background: "#0a0505",
      foreground: "#fff0f0",
      muted: "#1a0f0f",
      mutedForeground: "#f87171",
      card: "#120a0a",
      cardForeground: "#fff0f0",
      popover: "#160c0c",
      popoverForeground: "#fff0f0",
      border: "#3b1515",
      input: "#1a0f0f",
      primary: "#dc2626",
      primaryForeground: "#fff0f0",
      secondary: "#1f1010",
      secondaryForeground: "#fff0f0",
      accent: "#ef4444",
      accentForeground: "#0a0505",
      destructive: "#fca5a5",
      destructiveForeground: "#0a0505",
      ring: "rgba(220, 38, 38, 0.5)",
      success: "#4ade80",
      warning: "#fbbf24",
      successForeground: "#0a0505",
      warningForeground: "#0a0505",
    },
  },

  // Matrix Green - Terminal/hacker style
  "matrix-green": {
    id: "matrix-green",
    name: "Matrix",
    icon: "💻",
    description: "Style terminal",
    headerColor: "#0a0f0a",
    colors: {
      background: "#0a0f0a",
      foreground: "#d1fae5",
      muted: "#0f1a0f",
      mutedForeground: "#4ade80",
      card: "#0d140d",
      cardForeground: "#d1fae5",
      popover: "#101810",
      popoverForeground: "#d1fae5",
      border: "#1a3a1a",
      input: "#0f1a0f",
      primary: "#22c55e",
      primaryForeground: "#0a0f0a",
      secondary: "#142014",
      secondaryForeground: "#d1fae5",
      accent: "#4ade80",
      accentForeground: "#0a0f0a",
      destructive: "#f87171",
      destructiveForeground: "#0a0f0a",
      ring: "rgba(34, 197, 94, 0.5)",
      success: "#10b981",
      warning: "#fbbf24",
      successForeground: "#0a0f0a",
      warningForeground: "#0a0f0a",
    },
  },

  // ============================================================================
  // VISUAL DESIGN SYSTEMS (VDS) - Revolutionary Themes
  // ============================================================================

  "brutalist-pharmacy": {
    id: "brutalist-pharmacy",
    name: "Brutalist Pharmacy",
    icon: "⬛",
    description: "Design suisse brut, high-contrast",
    headerColor: "#ffffff",
    colors: {
      background: "#ffffff",
      foreground: "#000000",
      muted: "#f5f5f5",
      mutedForeground: "#666666",
      card: "#ffffff",
      cardForeground: "#000000",
      popover: "#ffffff",
      popoverForeground: "#000000",
      border: "#000000",
      input: "#ffffff",
      primary: "#000000",
      primaryForeground: "#ffffff",
      secondary: "#f5f5f5",
      secondaryForeground: "#000000",
      accent: "#ff0000",
      accentForeground: "#ffffff",
      destructive: "#ff0000",
      destructiveForeground: "#ffffff",
      ring: "rgba(0, 0, 0, 0.4)",
      success: "#000000",
      warning: "#ff0000",
      successForeground: "#ffffff",
      warningForeground: "#ffffff",
    },
  },

  "luxury-spa": {
    id: "luxury-spa",
    name: "Luxury Spa",
    icon: "✨",
    description: "Sérénité et minimalisme chaud",
    headerColor: "#f8f6f3",
    colors: {
      background: "#f8f6f3",
      foreground: "#3d3226",
      muted: "#ebe7e0",
      mutedForeground: "#7a6f5d",
      card: "#f8f6f3",
      cardForeground: "#3d3226",
      popover: "#f8f6f3",
      popoverForeground: "#3d3226",
      border: "#d4cec0",
      input: "#ebe7e0",
      primary: "#b8a58e",
      primaryForeground: "#3d3226",
      secondary: "#e8d4bb",
      secondaryForeground: "#3d3226",
      accent: "#d4a574",
      accentForeground: "#3d3226",
      destructive: "#a85443",
      destructiveForeground: "#f8f6f3",
      ring: "rgba(184, 165, 142, 0.4)",
      success: "#8a9a7e",
      warning: "#d4a574",
      successForeground: "#f8f6f3",
      warningForeground: "#3d3226",
    },
  },

  "cyberpunk-terminal": {
    id: "cyberpunk-terminal",
    name: "Cyberpunk Terminal",
    icon: "🔮",
    description: "Grilles néon, esthétique hacker",
    headerColor: "#0a0a0f",
    colors: {
      background: "#0a0a0f",
      foreground: "#00ff88",
      muted: "#1a1a2e",
      mutedForeground: "#00ff8880",
      card: "#0a0a0f",
      cardForeground: "#00ff88",
      popover: "#0a0a0f",
      popoverForeground: "#00ff88",
      border: "#00ff88",
      input: "#1a1a2e",
      primary: "#ff007f",
      primaryForeground: "#0a0a0f",
      secondary: "#9d00ff",
      secondaryForeground: "#0a0a0f",
      accent: "#00f0ff",
      accentForeground: "#0a0a0f",
      destructive: "#ff0055",
      destructiveForeground: "#0a0a0f",
      ring: "rgba(255, 0, 127, 0.5)",
      success: "#00ff88",
      warning: "#ffaa00",
      successForeground: "#0a0a0f",
      warningForeground: "#0a0a0f",
    },
  },

  "scandinavian-minimal": {
    id: "scandinavian-minimal",
    name: "Scandinavian Minimal",
    icon: "🏔️",
    description: "Hygge et beauté fonctionnelle",
    headerColor: "#fafafa",
    colors: {
      background: "#fafafa",
      foreground: "#1a1a1a",
      muted: "#f0f0f0",
      mutedForeground: "#737373",
      card: "#fafafa",
      cardForeground: "#1a1a1a",
      popover: "#fafafa",
      popoverForeground: "#1a1a1a",
      border: "#e5e5e5",
      input: "#f0f0f0",
      primary: "#4a5568",
      primaryForeground: "#fafafa",
      secondary: "#d4a574",
      secondaryForeground: "#1a1a1a",
      accent: "#8b7355",
      accentForeground: "#fafafa",
      destructive: "#dc2626",
      destructiveForeground: "#fafafa",
      ring: "rgba(74, 85, 104, 0.4)",
      success: "#059669",
      warning: "#d97706",
      successForeground: "#fafafa",
      warningForeground: "#fafafa",
    },
  },

  "memphis-retro": {
    id: "memphis-retro",
    name: "Memphis Retro",
    icon: "🎨",
    description: "Années 80/90, chaos ludique",
    headerColor: "#fff5e1",
    colors: {
      background: "#fff5e1",
      foreground: "#2d2d2d",
      muted: "#ffe8d6",
      mutedForeground: "#666666",
      card: "#fff5e1",
      cardForeground: "#2d2d2d",
      popover: "#fff5e1",
      popoverForeground: "#2d2d2d",
      border: "#2d2d2d",
      input: "#ffe8d6",
      primary: "#ff6b9d",
      primaryForeground: "#2d2d2d",
      secondary: "#ffbd00",
      secondaryForeground: "#2d2d2d",
      accent: "#00d9ff",
      accentForeground: "#2d2d2d",
      destructive: "#ff3366",
      destructiveForeground: "#fff5e1",
      ring: "rgba(255, 107, 157, 0.5)",
      success: "#00d9a3",
      warning: "#ffbd00",
      successForeground: "#2d2d2d",
      warningForeground: "#2d2d2d",
    },
  },

  "neomorphism": {
    id: "neomorphism",
    name: "Neomorphism",
    icon: "🌊",
    description: "Soft UI, profondeur tactile",
    headerColor: "#e0e5ec",
    colors: {
      background: "#e0e5ec",
      foreground: "#2d3748",
      muted: "#d1d9e6",
      mutedForeground: "#4a5568",
      card: "#e0e5ec",
      cardForeground: "#2d3748",
      popover: "#e0e5ec",
      popoverForeground: "#2d3748",
      border: "#c8d0df",
      input: "#d1d9e6",
      primary: "#6366f1",
      primaryForeground: "#e0e5ec",
      secondary: "#8b5cf6",
      secondaryForeground: "#e0e5ec",
      accent: "#a78bfa",
      accentForeground: "#e0e5ec",
      destructive: "#ef4444",
      destructiveForeground: "#e0e5ec",
      ring: "rgba(99, 102, 241, 0.4)",
      success: "#10b981",
      warning: "#f59e0b",
      successForeground: "#e0e5ec",
      warningForeground: "#e0e5ec",
    },
  },

  "vaporwave-aesthetic": {
    id: "vaporwave-aesthetic",
    name: "Vaporwave",
    icon: "🌈",
    description: "Rêve numérique des années 90",
    headerColor: "#1a0033",
    colors: {
      background: "#1a0033",
      foreground: "#ff71ce",
      muted: "#3d2563",
      mutedForeground: "#b19cd9",
      card: "#2d1b4e",
      cardForeground: "#ff71ce",
      popover: "#2d1b4e",
      popoverForeground: "#ff71ce",
      border: "#b967ff",
      input: "#2d1b4e",
      primary: "#01cdfe",
      primaryForeground: "#1a0033",
      secondary: "#b967ff",
      secondaryForeground: "#ffffff",
      accent: "#05ffa1",
      accentForeground: "#1a0033",
      destructive: "#ff6b9d",
      destructiveForeground: "#ffffff",
      ring: "rgba(1, 205, 254, 0.5)",
      success: "#05ffa1",
      warning: "#fffb96",
      successForeground: "#1a0033",
      warningForeground: "#1a0033",
    },
  },

  "industrial-concrete": {
    id: "industrial-concrete",
    name: "Industrial",
    icon: "🏭",
    description: "Brut industriel, béton exposé",
    headerColor: "#d4d4d4",
    colors: {
      background: "#d4d4d4",
      foreground: "#1c1c1c",
      muted: "#bfbfbf",
      mutedForeground: "#5a5a5a",
      card: "#e8e8e8",
      cardForeground: "#1c1c1c",
      popover: "#e8e8e8",
      popoverForeground: "#1c1c1c",
      border: "#8a8a8a",
      input: "#e8e8e8",
      primary: "#3a3a3a",
      primaryForeground: "#ffffff",
      secondary: "#5a5a5a",
      secondaryForeground: "#ffffff",
      accent: "#c85a54",
      accentForeground: "#ffffff",
      destructive: "#c85a54",
      destructiveForeground: "#ffffff",
      ring: "rgba(58, 58, 58, 0.4)",
      success: "#4a7c59",
      warning: "#c89b3c",
      successForeground: "#ffffff",
      warningForeground: "#ffffff",
    },
  },

  "neon-tokyo": {
    id: "neon-tokyo",
    name: "Neon Tokyo",
    icon: "🏮",
    description: "Enseigne japonaise, néons vifs",
    headerColor: "#0d0d0d",
    colors: {
      background: "#0d0d0d",
      foreground: "#ffffff",
      muted: "#2d2d2d",
      mutedForeground: "#a0a0a0",
      card: "#1a1a1a",
      cardForeground: "#ffffff",
      popover: "#1a1a1a",
      popoverForeground: "#ffffff",
      border: "#ff2a6d",
      input: "#1a1a1a",
      primary: "#ff2a6d",
      primaryForeground: "#0d0d0d",
      secondary: "#d1f300",
      secondaryForeground: "#0d0d0d",
      accent: "#00fff5",
      accentForeground: "#0d0d0d",
      destructive: "#ff006e",
      destructiveForeground: "#ffffff",
      ring: "rgba(0, 255, 245, 0.5)",
      success: "#00ff9f",
      warning: "#ffbd00",
      successForeground: "#0d0d0d",
      warningForeground: "#0d0d0d",
    },
  },

  "organic-nature": {
    id: "organic-nature",
    name: "Organic Nature",
    icon: "🌿",
    description: "Tons terre, design durable",
    headerColor: "#f5f0e8",
    colors: {
      background: "#f5f0e8",
      foreground: "#2d3319",
      muted: "#ebe5da",
      mutedForeground: "#6b7558",
      card: "#faf7f2",
      cardForeground: "#2d3319",
      popover: "#faf7f2",
      popoverForeground: "#2d3319",
      border: "#c8bcaa",
      input: "#faf7f2",
      primary: "#5f7a3d",
      primaryForeground: "#ffffff",
      secondary: "#8b7355",
      secondaryForeground: "#ffffff",
      accent: "#c17c4a",
      accentForeground: "#ffffff",
      destructive: "#a84432",
      destructiveForeground: "#ffffff",
      ring: "rgba(95, 122, 61, 0.4)",
      success: "#5f7a3d",
      warning: "#d4a373",
      successForeground: "#ffffff",
      warningForeground: "#2d3319",
    },
  },
};

export const themeIds = Object.keys(themes) as string[];
export const defaultThemeId = "ice-glass";
